version: "3"

services:
  db:
    image: postgres:15
    env_file:
      - ./.envs/.env.postgres
    ports:
      - 5433:5432
    networks:
      - "local-development"

  tests:
    build:
      dockerfile: ./deployment/testing/Dockerfile
    env_file:
      - ./.envs/.env.base
      - ./.envs/.env.test
    depends_on:
      - db
    ports:
      - 9001:9000
    networks:
      - "local-development"

  app:
    build:
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=docker
    env_file:
      - ./.envs/.env.docker
    ports:
      - 9001:9000
    networks:
      - "local-development"
    depends_on:
      - db

  linter:
    build:
      dockerfile: deployment/linter/Dockerfile
networks:
  local-development:
